# Generated by Django 5.2.8 on 2026-04-22 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('bride', 'Bride'), ('groom', 'Groom'), ('guardian', 'Guardian'), ('admin', 'Admin')], max_length=20, unique=True)),
            ],
            options={
                'db_table': 'accounts_role',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='analytics_tracking',
        ),
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='marketing_emails',
        ),
        migrations.RemoveField(
            model_name='user',
            name='public_profile',
        ),
        migrations.RemoveField(
            model_name='user',
            name='push_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='share_with_vendors',
        ),
        migrations.RemoveField(
            model_name='user',
            name='sms_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_tier',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role'),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_settings',
            },
        ),
    ]
