# Generated by Django 5.2.8 on 2026-04-22 16:10

from django.db import migrations


def create_default_roles_and_update_users(apps, schema_editor):
    """Create default roles and assign them to existing users"""
    Role = apps.get_model('accounts', 'Role')
    User = apps.get_model('accounts', 'User')
    Settings = apps.get_model('accounts', 'Settings')
    
    # Create default roles
    bride_role, created = Role.objects.get_or_create(name='bride')
    groom_role, created = Role.objects.get_or_create(name='groom')
    guardian_role, created = Role.objects.get_or_create(name='guardian')
    admin_role, created = Role.objects.get_or_create(name='admin')
    
    # Assign default role to existing users (use 'bride' as default)
    default_role = bride_role
    User.objects.filter(role__isnull=True).update(role=default_role)
    
    # Create settings for all users who don't have them
    for user in User.objects.all():
        Settings.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_role_remove_user_analytics_tracking_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_roles_and_update_users),
    ]
