# Generated by Django 5.2.8 on 2026-04-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('rsvp_date', models.DateField(blank=True, null=True)),
                ('plus_one', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=100, null=True)),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('other', 'Other')], default='friend', max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('invitation_sent', models.BooleanField(default=False)),
                ('invitation_sent_date', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_date', models.DateTimeField(blank=True, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='weddings.wedding')),
            ],
            options={
                'db_table': 'guests_guest',
                'ordering': ['name'],
            },
        ),
    ]
