# Generated by Django 5.2.8 on 2026-04-22 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
        ('weddings', '0003_populate_wedding_core_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'guests_meal',
            },
        ),
        migrations.CreateModel(
            name='RsvpStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'guests_rsvp_status',
            },
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='name',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='plus_one',
        ),
        migrations.RemoveField(
            model_name='guest',
            name='plus_one_name',
        ),
        migrations.AddField(
            model_name='guest',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='guest',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='guest',
            name='rsvp_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='guests.rsvpstatus'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('capacity', models.PositiveIntegerField()),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='weddings.wedding')),
            ],
            options={
                'db_table': 'guests_table',
                'ordering': ['wedding', 'table_number'],
                'unique_together': {('wedding', 'table_number')},
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_guests', to='guests.table'),
        ),
        migrations.CreateModel(
            name='GuestMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_preferences', to='guests.guest')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_assignments', to='guests.meal')),
            ],
            options={
                'db_table': 'guests_guest_meal',
                'unique_together': {('guest', 'meal')},
            },
        ),
    ]
