# Generated by Django 5.2.8 on 2026-04-22 16:20

from django.db import migrations


def populate_guests_data(apps, schema_editor):
    """Create default RSVP statuses, meals, and migrate guest names"""
    RsvpStatus = apps.get_model('guests', 'RsvpStatus')
    Meal = apps.get_model('guests', 'Meal')
    Guest = apps.get_model('guests', 'Guest')
    
    # Create default RSVP statuses
    statuses = ['pending', 'confirmed', 'declined']
    for status_name in statuses:
        RsvpStatus.objects.get_or_create(name=status_name)
    
    # Create default meal options
    meals = [
        'Chicken', 'Beef', 'Fish', 'Vegetarian', 'Vegan',
        'Gluten-Free', 'Kids Meal', 'No Meal'
    ]
    for meal_name in meals:
        Meal.objects.get_or_create(name=meal_name)
    
    # Migrate existing guest names from old name field to first_name/last_name
    # Note: The old name field was removed, so we need to handle this carefully
    # For now, we'll set a default first_name since we can't access the old field
    pending_status = RsvpStatus.objects.get(name='pending')
    for guest in Guest.objects.all():
        if not guest.first_name and not guest.last_name:
            # Set a default name since we can't access the old name field
            guest.first_name = 'Guest'
            guest.last_name = f'#{guest.id}'
            guest.rsvp_status = pending_status
            guest.save()


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_meal_rsvpstatus_alter_guest_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_guests_data),
    ]
