# Generated by Django 5.2.8 on 2026-04-21 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride_name', models.CharField(blank=True, max_length=100, null=True)),
                ('groom_name', models.CharField(blank=True, max_length=100, null=True)),
                ('partner_name', models.CharField(blank=True, max_length=100, null=True)),
                ('wedding_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
                ('venue_address', models.TextField(blank=True, null=True)),
                ('guest_count', models.PositiveIntegerField(default=0)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('website_domain', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wedding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weddings_wedding',
            },
        ),
    ]
