# Generated by Django 5.2.8 on 2026-04-22 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'weddings_venue',
            },
        ),
        migrations.CreateModel(
            name='VenueAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'weddings_venue_amenity',
            },
        ),
        migrations.CreateModel(
            name='VenueCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('restaurant', 'Restaurant'), ('outdoor', 'Outdoor Venue'), ('church', 'Church'), ('beach', 'Beach'), ('garden', 'Garden'), ('ballroom', 'Ballroom'), ('other', 'Other')], max_length=20)),
                ('address', models.TextField()),
                ('capacity_min', models.PositiveIntegerField()),
                ('capacity_max', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'weddings_venue_catalog',
            },
        ),
        migrations.CreateModel(
            name='WeddingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'weddings_wedding_status',
            },
        ),
        migrations.RenameField(
            model_name='wedding',
            old_name='bride_name',
            new_name='theme',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='groom_name',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='guest_count',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='partner_name',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='venue_address',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='website_domain',
        ),
        migrations.RemoveField(
            model_name='wedding',
            name='website_url',
        ),
        migrations.AlterField(
            model_name='wedding',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weddings', to='weddings.venue'),
        ),
        migrations.AddField(
            model_name='venue',
            name='venue_catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wedding_venues', to='weddings.venuecatalog'),
        ),
        migrations.AlterField(
            model_name='wedding',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='weddings.weddingstatus'),
        ),
        migrations.CreateModel(
            name='VenueAmenityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_mappings', to='weddings.venueamenity')),
                ('venue_catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_mappings', to='weddings.venuecatalog')),
            ],
            options={
                'db_table': 'weddings_venue_amenity_map',
                'unique_together': {('venue_catalog', 'amenity')},
            },
        ),
    ]
