# Generated by Django 5.2.8 on 2026-04-22 16:16

from django.db import migrations


def create_wedding_core_data(apps, schema_editor):
    """Create default wedding statuses and venue amenities"""
    WeddingStatus = apps.get_model('weddings', 'WeddingStatus')
    VenueAmenity = apps.get_model('weddings', 'VenueAmenity')
    
    # Create default wedding statuses
    statuses = ['planning', 'confirmed', 'completed', 'cancelled']
    for status_name in statuses:
        WeddingStatus.objects.get_or_create(name=status_name)
    
    # Create default venue amenities
    amenities = [
        'Parking', 'WiFi', 'Air Conditioning', 'Outdoor Space', 
        'Catering Kitchen', 'Dance Floor', 'Bar', 'Audio/Visual Equipment',
        'Bridal Suite', 'Accessibility', 'Garden', 'Pool', 'Beach Access',
        'Mountain View', 'City View', 'Historic Building'
    ]
    for amenity_name in amenities:
        VenueAmenity.objects.get_or_create(name=amenity_name)


class Migration(migrations.Migration):

    dependencies = [
        ('weddings', '0002_venue_venueamenity_venuecatalog_weddingstatus_and_more'),
    ]

    operations = [
        migrations.RunPython(create_wedding_core_data),
    ]
