# Generated by Django 5.2.8 on 2026-04-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendors', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('venue', 'Venue'), ('catering', 'Catering'), ('photography', 'Photography'), ('videography', 'Videography'), ('florist', 'Florist'), ('music', 'Music/Entertainment'), ('cake', 'Cake'), ('decorations', 'Decorations'), ('attire', 'Attire'), ('rings', 'Rings'), ('transportation', 'Transportation'), ('accommodation', 'Accommodation'), ('invitations', 'Invitations'), ('gifts', 'Gifts'), ('other', 'Other')], max_length=20)),
                ('estimated_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='vendors.vendor')),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='weddings.wedding')),
            ],
            options={
                'db_table': 'expenses_expense',
                'ordering': ['-expense_date', 'category', 'description'],
            },
        ),
    ]
