# Generated by Django 5.2.8 on 2026-04-22 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('weddings', '0003_populate_wedding_core_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'expenses_expense_status',
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', 'budget_category', 'title']},
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='estimated_cost',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='amount_paid',
            new_name='paid_amount',
        ),
        migrations.RenameField(
            model_name='expense',
            old_name='description',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='payment_status',
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='weddings.wedding')),
            ],
            options={
                'db_table': 'expenses_budget_category',
                'unique_together': {('wedding', 'name')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='budget_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.budgetcategory'),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='expenses.expensestatus'),
        ),
    ]
