# Generated by Django 5.2.8 on 2026-04-22 16:34

from django.db import migrations


def populate_expenses_data(apps, schema_editor):
    """Create default expense statuses and budget categories"""
    ExpenseStatus = apps.get_model('expenses', 'ExpenseStatus')
    BudgetCategory = apps.get_model('expenses', 'BudgetCategory')
    Wedding = apps.get_model('weddings', 'Wedding')
    
    # Create default expense statuses
    statuses = ['pending', 'partial', 'paid', 'overdue']
    for status_name in statuses:
        ExpenseStatus.objects.get_or_create(name=status_name)
    
    # Create default budget categories for each wedding
    default_categories = [
        ('Venue', 5000.00),
        ('Catering', 8000.00),
        ('Photography', 3000.00),
        ('Videography', 2000.00),
        ('Florist', 2000.00),
        ('Music/Entertainment', 1500.00),
        ('Cake', 500.00),
        ('Decorations', 1500.00),
        ('Attire', 2000.00),
        ('Rings', 3000.00),
        ('Transportation', 1000.00),
        ('Accommodation', 2000.00),
        ('Invitations', 500.00),
        ('Gifts', 1000.00),
        ('Other', 2000.00),
    ]
    
    for wedding in Wedding.objects.all():
        for category_name, allocated_amount in default_categories:
            BudgetCategory.objects.get_or_create(
                wedding=wedding,
                name=category_name,
                defaults={'allocated_amount': allocated_amount}
            )


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expensestatus_alter_expense_options_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_expenses_data),
    ]
