# Generated by Django 5.2.8 on 2026-04-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('vendor_type', models.CharField(choices=[('venue', 'Venue'), ('photography', 'Photography'), ('catering', 'Catering'), ('florist', 'Florist'), ('music', 'Music/Entertainment'), ('cake', 'Cake'), ('decorations', 'Decorations'), ('transportation', 'Transportation'), ('officiant', 'Officiant'), ('other', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('deposit_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('booking_date', models.DateField(blank=True, null=True)),
                ('contract_signed', models.BooleanField(default=False)),
                ('contract_signed_date', models.DateField(blank=True, null=True)),
                ('services_provided', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_contact_date', models.DateTimeField(blank=True, null=True)),
                ('next_follow_up', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='weddings.wedding')),
            ],
            options={
                'db_table': 'vendors_vendor',
                'ordering': ['vendor_type', 'name'],
            },
        ),
    ]
