# Generated by Django 5.2.8 on 2026-04-22 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=200)),
                ('price_range', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'vendors_vendor_catalog',
            },
        ),
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'vendors_vendor_category',
            },
        ),
        migrations.CreateModel(
            name='VendorStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'vendors_vendor_status',
            },
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'ordering': ['vendor_catalog__category', 'vendor_catalog__name']},
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='cost',
            new_name='actual_cost',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='deposit_paid',
            new_name='cost_estimate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='booking_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contract_signed',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='contract_signed_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='last_contact_date',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='next_follow_up',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='services_provided',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_type',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='website',
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_catalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wedding_vendors', to='vendors.vendorcatalog'),
        ),
        migrations.AddField(
            model_name='vendorcatalog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalog_vendors', to='vendors.vendorcategory'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vendors.vendorstatus'),
        ),
    ]
