# Generated by Django 5.2.8 on 2026-04-22 16:25

from django.db import migrations


def populate_vendors_data(apps, schema_editor):
    """Create default vendor categories, statuses, and catalog entries"""
    VendorCategory = apps.get_model('vendors', 'VendorCategory')
    VendorStatus = apps.get_model('vendors', 'VendorStatus')
    VendorCatalog = apps.get_model('vendors', 'VendorCatalog')
    
    # Create default vendor categories
    categories = [
        'Photography', 'Catering', 'Florist', 'Music/Entertainment',
        'Cake', 'Decorations', 'Transportation', 'Officiant',
        'Venue', 'Videography', 'Hair/Makeup', 'Other'
    ]
    for category_name in categories:
        VendorCategory.objects.get_or_create(name=category_name)
    
    # Create default vendor statuses
    statuses = ['pending', 'contacted', 'confirmed', 'completed', 'cancelled']
    for status_name in statuses:
        VendorStatus.objects.get_or_create(name=status_name)
    
    # Create sample vendor catalog entries
    photography_cat = VendorCategory.objects.get(name='Photography')
    catering_cat = VendorCategory.objects.get(name='Catering')
    florist_cat = VendorCategory.objects.get(name='Florist')
    
    sample_vendors = [
        {
            'category': photography_cat,
            'name': 'Eternal Moments Photography',
            'contact': 'contact@eternalmoments.com | 555-0101',
            'price_range': 2500.00,
            'rating': 4.8
        },
        {
            'category': photography_cat,
            'name': 'Captured Love Studios',
            'contact': 'info@capturedlove.com | 555-0102',
            'price_range': 3000.00,
            'rating': 4.9
        },
        {
            'category': catering_cat,
            'name': 'Gourmet Delights Catering',
            'contact': 'events@gourmetdelights.com | 555-0201',
            'price_range': 5000.00,
            'rating': 4.7
        },
        {
            'category': catering_cat,
            'name': 'Taste of Heaven Catering',
            'contact': 'book@tasteofheaven.com | 555-0202',
            'price_range': 4500.00,
            'rating': 4.6
        },
        {
            'category': florist_cat,
            'name': 'Bloom & Blossom Florists',
            'contact': 'weddings@bloomblossom.com | 555-0301',
            'price_range': 1500.00,
            'rating': 4.8
        },
        {
            'category': florist_cat,
            'name': 'Floral Elegance',
            'contact': 'info@floralelegance.com | 555-0302',
            'price_range': 2000.00,
            'rating': 4.9
        }
    ]
    
    for vendor_data in sample_vendors:
        VendorCatalog.objects.get_or_create(
            name=vendor_data['name'],
            defaults=vendor_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendorcatalog_vendorcategory_vendorstatus_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_vendors_data),
    ]
