"""
Django settings for wedding_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qi@2=5zts-k4-3h04$&uwys#34immhb*v3@-bxwf#x0uk=a=tr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'drf_spectacular',
    'accounts',
    'weddings',
    'guests',
    'vendors',
    'expenses',
    'wedding_cards',
    'timeline',
    'media',
    'documents',
    'tasks',
    'internal_admin',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wedding_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'internal_admin' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wedding_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Jazzmin Configuration
JAZZMIN_SETTINGS = {
    'site_title': 'Saanjh Admin',
    'site_header': 'Saanjh Wedding Planning',
    'site_brand': 'Saanjh',
    'welcome_sign': 'Welcome to Saanjh Wedding Planning Admin',
    'copyright': 'Saanjh Wedding Planning Platform',
    'navigation': [
        {'app': 'accounts', 'label': '👤 Accounts', 'models': [
            {'model': 'accounts.user', 'label': 'Users'},
            {'model': 'accounts.role', 'label': 'Roles'},
            {'model': 'accounts.settings', 'label': 'User Settings'},
        ]},
        {'app': 'weddings', 'label': '💒 Weddings', 'models': [
            {'model': 'weddings.wedding', 'label': 'Weddings'},
            {'model': 'weddings.weddingstatus', 'label': 'Wedding Status'},
            {'model': 'weddings.venuecatalog', 'label': 'Venue Catalog'},
            {'model': 'weddings.venue', 'label': 'Venues'},
        ]},
        {'app': 'guests', 'label': '👥 Guests', 'models': [
            {'model': 'guests.guest', 'label': 'Guests'},
            {'model': 'guests.rsvpstatus', 'label': 'RSVP Status'},
            {'model': 'guests.table', 'label': 'Tables'},
            {'model': 'guests.meal', 'label': 'Meal Options'},
        ]},
        {'app': 'expenses', 'label': '💰 Expenses', 'models': [
            {'model': 'expenses.expense', 'label': 'Expenses'},
            {'model': 'expenses.expensestatus', 'label': 'Expense Status'},
            {'model': 'expenses.budgetcategory', 'label': 'Budget Categories'},
        ]},
        {'app': 'vendors', 'label': '🏪 Vendors', 'models': [
            {'model': 'vendors.vendor', 'label': 'Vendors'},
            {'model': 'vendors.vendorstatus', 'label': 'Vendor Status'},
            {'model': 'vendors.vendorcategory', 'label': 'Vendor Categories'},
            {'model': 'vendors.vendorcatalog', 'label': 'Vendor Catalog'},
        ]},
        {'app': 'timeline', 'label': '📅 Timeline', 'models': [
            {'model': 'timeline.timeline', 'label': 'Timelines'},
            {'model': 'timeline.timelineevent', 'label': 'Timeline Events'},
            {'model': 'timeline.timestatus', 'label': 'Timeline Status'},
        ]},
    ],
    'icons': {
        'accounts': 'fas fa-user-circle',
        'weddings': 'fas fa-heart',
        'guests': 'fas fa-users',
        'expenses': 'fas fa-dollar-sign',
        'vendors': 'fas fa-store',
        'timeline': 'fas fa-calendar-alt',
    },
    'default_model_icons': {
        'User': 'fas fa-user',
        'Role': 'fas fa-user-tag',
        'Settings': 'fas fa-cog',
        'Wedding': 'fas fa-heart',
        'WeddingStatus': 'fas fa-flag',
        'VenueCatalog': 'fas fa-building',
        'Venue': 'fas fa-map-marker-alt',
        'Guest': 'fas fa-user',
        'RsvpStatus': 'fas fa-envelope',
        'Table': 'fas fa-chair',
        'Meal': 'fas fa-utensils',
        'Expense': 'fas fa-receipt',
        'ExpenseStatus': 'fas fa-check-circle',
        'BudgetCategory': 'fas fa-tags',
        'Vendor': 'fas fa-store',
        'VendorStatus': 'fas fa-clipboard-check',
        'VendorCategory': 'fas fa-th-large',
        'VendorCatalog': 'fas fa-book',
        'Timeline': 'fas fa-calendar',
        'TimelineEvent': 'fas fa-clock',
        'TimelineStatus': 'fas fa-tasks',
    },
    'hide_models': ['auth.Group', 'auth.Permission'],
    'search_url': '/admin/',
    'user_avatar': 'img/jazzmin_avatar.png',
    'topmenu_links': [
        {'name': 'Home', 'url': '/', 'icon': 'fas fa-home'},
        {'name': 'Table Schemas', 'url': '/api/docs/', 'icon': 'fas fa-database'},
        {'name': 'Swagger UI', 'url': '/api/swagger/', 'icon': 'fas fa-code'},
    ],
    'related_modal_active': True,
    'actions': {
        'accounts.user': ['mark_active', 'mark_inactive'],
        'guests.guest': ['mark_rsvp_confirmed', 'send_invitation_reminder'],
        'expenses.expense': ['mark_as_paid'],
    },
}

# drf-spectacular configuration
SPECTACULAR_SETTINGS = {
    'TITLE': 'Saanjh Wedding Planning API',
    'DESCRIPTION': 'API documentation for Saanjh wedding planning platform',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'COMPONENT_NO_REQUEST_BODY': True,
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3001",
]

CORS_ALLOW_CREDENTIALS = True

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'
