# Generated by Django 5.2.8 on 2026-04-22 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0003_populate_wedding_core_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'media_media_type',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file_url', models.URLField()),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='weddings.wedding')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='media_files', to='media.mediatype')),
            ],
            options={
                'db_table': 'media_media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
