# Generated by Django 5.2.8 on 2026-04-22 16:37

from django.db import migrations


def populate_media_data(apps, schema_editor):
    """Create default media types"""
    MediaType = apps.get_model('media', 'MediaType')
    
    # Create default media types
    media_types = ['photo', 'video', 'document', 'audio']
    for media_type_name in media_types:
        MediaType.objects.get_or_create(name=media_type_name)


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_media_data),
    ]
