# Generated by Django 5.2.8 on 2026-04-28 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_populate_media_data'),
        ('weddings', '0003_populate_wedding_core_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('pre-wedding', 'Pre-Wedding'), ('wedding-day', 'Wedding Day'), ('post-wedding', 'Post-Wedding'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='weddings.wedding')),
            ],
            options={
                'db_table': 'media_album',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlbumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='media.album')),
            ],
            options={
                'db_table': 'media_album_tag',
            },
        ),
        migrations.CreateModel(
            name='MediaAlbum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='media.album')),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_links', to='media.media')),
            ],
            options={
                'db_table': 'media_media_album',
                'unique_together': {('media', 'album')},
            },
        ),
    ]
