# Generated by Django 5.2.8 on 2026-04-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('weddings', '0003_populate_wedding_core_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'timeline_timeline_status',
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wedding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='weddings.wedding')),
            ],
            options={
                'db_table': 'timeline_timeline',
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('timeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.timeline')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='timeline.timelinestatus')),
            ],
            options={
                'db_table': 'timeline_timeline_event',
                'ordering': ['event_date', 'start_time'],
            },
        ),
    ]
