# Generated by Django 5.2.8 on 2026-04-22 16:28

from django.db import migrations


def populate_timeline_data(apps, schema_editor):
    """Create default timeline statuses"""
    TimelineStatus = apps.get_model('timeline', 'TimelineStatus')
    
    # Create default timeline statuses
    statuses = ['pending', 'in_progress', 'completed', 'cancelled']
    for status_name in statuses:
        TimelineStatus.objects.get_or_create(name=status_name)


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_timeline_data),
    ]
