# Generated by Django 5.2.8 on 2026-04-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_populate_timeline_data'),
        ('weddings', '0003_populate_wedding_core_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timelineevent',
            options={'ordering': ['date', 'time']},
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('payment', 'Payment'), ('deadline', 'Deadline'), ('event', 'Event'), ('task', 'Task'), ('reminder', 'Reminder')], default='task', max_length=20),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='wedding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='weddings.wedding'),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='end_time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='start_time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
    ]
