# Generated by Django 5.2.8 on 2026-04-25 07:58

from django.db import migrations
from datetime import date, timedelta


def migrate_timeline_event_data(apps, schema_editor):
    """Migrate data from legacy fields to new fields and update dates to current"""
    TimelineEvent = apps.get_model('timeline', 'TimelineEvent')
    today = date.today()

    # Get all events and sort by date
    events = list(TimelineEvent.objects.all().order_by('event_date'))

    if not events:
        return

    # Define the new timeline dates (within ±1 month of current date)
    # Current date is 2026-04-25, so we want dates from 2026-04-10 to 2026-05-25
    new_dates = [
        today - timedelta(days=15),  # 15 days ago
        today - timedelta(days=10),  # 10 days ago
        today - timedelta(days=5),   # 5 days ago
        today,                        # today
        today + timedelta(days=15),  # 15 days from now
        today + timedelta(days=30),  # 30 days from now (wedding day)
    ]

    for i, event in enumerate(events):
        # Copy data from legacy fields to new fields
        if event.event_date and not event.date:
            event.date = event.event_date
        if event.start_time and not event.time:
            event.time = event.start_time

        # Set default values for new fields if not set
        if not event.type:
            event.type = 'task'
        if not event.priority:
            event.priority = 'medium'

        # Set new date from the predefined list
        if i < len(new_dates):
            event.date = new_dates[i]

        event.save(update_fields=['date', 'time', 'type', 'priority'])


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_alter_timelineevent_options_timelineevent_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_timeline_event_data, migrations.RunPython.noop),
    ]
