# Generated by Django 5.2.8 on 2026-04-21 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guests', '0001_initial'),
        ('weddings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.IntegerField(choices=[(1, 'Elegant Classic'), (2, 'Modern Minimal'), (3, 'Romantic Floral'), (4, 'Vintage Charm'), (5, 'Beach Theme'), (6, 'Rustic Country')], default=1)),
                ('couple_names', models.CharField(max_length=200)),
                ('wedding_details', models.TextField()),
                ('primary_color', models.CharField(default='#8B5CF6', max_length=7)),
                ('font_style', models.CharField(choices=[('elegant', 'Elegant'), ('modern', 'Modern'), ('playful', 'Playful'), ('vintage', 'Vintage'), ('minimal', 'Minimal')], default='elegant', max_length=20)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('allow_guest_photos', models.BooleanField(default=True)),
                ('require_rsvp', models.BooleanField(default=True)),
                ('send_reminders', models.BooleanField(default=True)),
                ('shareable_link', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wedding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_cards', to='weddings.wedding')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingCardAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_views', models.PositiveIntegerField(default=0)),
                ('unique_views', models.PositiveIntegerField(default=0)),
                ('total_rsvps', models.PositiveIntegerField(default=0)),
                ('confirmed_rsvps', models.PositiveIntegerField(default=0)),
                ('declined_rsvps', models.PositiveIntegerField(default=0)),
                ('total_photos_uploaded', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('wedding_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='wedding_cards.weddingcard')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingCardGuest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('rsvp_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('rsvp_date', models.DateTimeField(auto_now=True)),
                ('plus_one', models.BooleanField(default=False)),
                ('plus_one_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dietary_restrictions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_photos', models.JSONField(blank=True, default=list)),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_rsvps', to='guests.guest')),
                ('wedding_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_guests', to='wedding_cards.weddingcard')),
            ],
        ),
    ]
